export { default as authRoutes } from './auth.routes.js';
export { default as bannerRoutes } from './banner.routes.js';
export { default as quoteRoutes } from './quote.routes.js';
export { default as contactRoutes } from './contact.routes.js';
export { default as statsRoutes } from './stats.routes.js';
export { default as trackRoutes } from './track.routes.js';
export { default as overviewRoutes } from './overview.routes.js';
export { default as amenityRoutes } from './amenity.routes.js';
export { default as galleryRoutes } from './gallery.routes.js';
export { default as perspectiveRoutes } from './perspective.routes.js';
export { bannerAdminRoutes, contactAdminRoutes, quoteAdminRoutes, overviewAdminRoutes, amenityAdminRoutes, galleryAdminRoutes, perspectiveAdminRoutes, telegramAdminRoutes } from './admin/index.js';
